"""Retrain the CSI300 model packs with a turnover cost inside the objective.

Cost-aware rerun (PROJECT_NOTES 7.29 open follow-up): the 5-seed B (DDR
naive + vol-targeted), C (TACR) and D (fuzzy + ablation) packs are retrained
at transaction_cost_bps = 1.0 so the policies RE-LEARN under cost instead of
being repriced from zero-cost checkpoints. Zero-cost checkpoints are left
untouched; at-cost checkpoints go to fields tagged `cost1`.

Steps (resumable — completed jobs are skipped by checkpoint existence):
    python scripts/retrain_at_cost.py --step ddr    (10 runs: 2 variants x 5 seeds)
    python scripts/retrain_at_cost.py --step tacr   (5 seeds)
    python scripts/retrain_at_cost.py --step d      (10 runs: 2 variants x 5 seeds)

Each job trains with the shared configs (same budgets/hyperparams as the
zero-cost packs) plus `--cost-bps 1` for DDR and dataset reward at 1 bps
(regenerated by scripts/csi300_pipeline.py --cost-bps 1.0) for TACR/D.
"""
from __future__ import annotations

import argparse
import ctypes
import subprocess
import sys
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SEEDS = [20260814, 1, 2, 3, 4]
COST_BPS = "1.0"


class _MEMORYSTATUSEX(ctypes.Structure):
    _fields_ = [
        ("dwLength", ctypes.c_ulong),
        ("dwMemoryLoad", ctypes.c_ulong),
        ("ullTotalPhys", ctypes.c_ulonglong),
        ("ullAvailPhys", ctypes.c_ulonglong),
        ("ullTotalPageFile", ctypes.c_ulonglong),
        ("ullAvailPageFile", ctypes.c_ulonglong),
        ("ullTotalVirtual", ctypes.c_ulonglong),
        ("ullAvailVirtual", ctypes.c_ulonglong),
        ("ullAvailExtendedVirtual", ctypes.c_ulonglong),
    ]


def free_commit_mb() -> float:
    """Available commit charge (MB) — what a torch CPU alloc actually hits."""
    st = _MEMORYSTATUSEX()
    st.dwLength = ctypes.sizeof(_MEMORYSTATUSEX)
    if not ctypes.windll.kernel32.GlobalMemoryStatusEx(ctypes.byref(st)):
        return float("nan")
    return st.ullAvailPageFile / (1024 * 1024)


def _wait_for_memory(floor_mb: float, max_wait_s: float = 900.0) -> None:
    """Block until free commit >= floor, else raise (protects against OOM)."""
    waited = 0.0
    while waited < max_wait_s:
        free = free_commit_mb()
        if free >= floor_mb:
            return
        print(f"[mem ] free commit {free:.0f} MB < floor {floor_mb:.0f} MB; "
              f"waiting 30s (total {waited:.0f}s)")
        time.sleep(30)
        waited += 30
    raise SystemExit(
        f"[mem ] free commit stayed below {floor_mb:.0f} MB for "
        f"{max_wait_s:.0f}s — aborting to avoid an OOM crash"
    )


def _jobs(step: str) -> list[dict]:
    ddr_root = ROOT / "src" / "models" / "ddr" / "checkpoints"
    if step == "ddr":
        return [
            {
                "cmd": [
                    sys.executable, "-m", "src.models.ddr.train",
                    "--seed", str(seed), "--cost-bps", COST_BPS,
                    *flags, "--tag", f"cost1/{run}/s{seed}",
                ],
                "ckpt": ddr_root / "cost1" / run / f"s{seed}" / "ddr_best.pt",
            }
            for run, flags in [("naive_new", ["--no-vol-targeting"]), ("vt", [])]
            for seed in SEEDS
        ]
    if step == "tacr":
        base = ROOT / "src" / "models" / "tacr" / "checkpoints" / "tacr" / "cost1"
        return [
            {
                "cmd": [
                    sys.executable, "-m", "src.models.tacr.train",
                    "--seed", str(seed), "--tag", "cost1",
                ],
                "ckpt": base / f"s{seed}" / "tacr_best.pt",
            }
            for seed in SEEDS
        ]
    if step == "d":
        base = ROOT / "src" / "models" / "d" / "checkpoints" / "cost1"
        return [
            {
                "cmd": [
                    sys.executable, "-m", "src.models.d.train",
                    "--variant", variant, "--seed", str(seed), "--tag", "cost1",
                ],
                "ckpt": base / variant / f"s{seed}" / "d_best.pt",
            }
            for variant in ("d", "d_minus_fuzzy")
            for seed in SEEDS
        ]
    raise SystemExit(f"unknown step: {step}")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--step", required=True, choices=("ddr", "tacr", "d"))
    parser.add_argument("--log", default=str(ROOT / "data" / "retrain_cost1.log"))
    parser.add_argument("--mem-floor-mb", type=float, default=700.0,
                        help="required free commit headroom before each job")
    parser.add_argument("--mem-max-wait-s", type=float, default=900.0)
    args = parser.parse_args()

    log = Path(args.log)
    log.parent.mkdir(parents=True, exist_ok=True)
    jobs = _jobs(args.step)
    done = 0
    with log.open("a", encoding="utf-8") as fh:
        for j in jobs:
            if j["ckpt"].exists():
                fh.write(f"[skip] exists {j['ckpt']}\n")
                fh.flush()
                done += 1
                continue
            _wait_for_memory(args.mem_floor_mb, args.mem_max_wait_s)
            fh.write(f"[run ] {' '.join(j['cmd'])}\n")
            fh.flush()
            r = subprocess.run(j["cmd"], cwd=ROOT, text=True)
            fh.write(f"[exit] {r.returncode} {j['ckpt']}\n")
            fh.flush()
            if r.returncode != 0 or not j["ckpt"].exists():
                fh.write(f"[FAIL] step={args.step} job={j['ckpt']} rc={r.returncode}\n")
                fh.flush()
                sys.exit(1)
            done += 1
    print(f"[retrain_at_cost] step={args.step} completed {done}/{len(jobs)} jobs")


if __name__ == "__main__":
    main()